#!/usr/bin/env sh

BUILD_DIR=$PWD/build
echo $BUILD_DIR

if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD_DIR
fi

cd ./elm-src
../node_modules/.bin/elm-esm make ./src/Main.elm --optimize --output=../build/elm.js
cd -
